server:
  listenAddr: 0.0.0.0
  listenPort: 8081
  tasks_log_file: tas
  tasks_log_split_interval: hour # 可选日/时 或日期


datasource:
  dirverName: mysql
  host: 124.222.238.134
  port: 5730
  database: db_flagship
  username: dba_yix
  password: xiangerfer
  charset: utf8
