server:
  listenAddr: 0.0.0.0
  listenPort: 8081
  tasks_log_file: tas
  tasks_log_split_interval: hour # 可选日/时 或日期

datasource:
  dirverName: mysql
  host: 0.0.0.0
  port: 1234
  database: db_name
  username: root
  password: 123456
  charset: utf8
